### ISSUE TITLE
Script Fails when scanning some BD

### ISSUE THREAD

**Issue by jmone1** [3ll3d00d/madmeasurer#10]
The Script stops running on some BD's as follows:
bluray.c:1413: libbluray version 1.1.1
bluray.c:1438: BLURAY initialized!
aacs.c:83: AACS\Unit_Key_RO.inf not found. No AACS protection.
navigation.c:476: Disc has no property(MainFeature)
navigation.c:479: Disc has no property(Playlists)
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature ∩╗┐<
navigation.c:513: Discarding on dupe clip (00000.mpls)
bluray.c:1553: BLURAY destroyed!
Traceback (most recent call last):
  File "madmeasurer\__main__.py", line 139, in <module>
  File "madmeasurer\__main__.py", line 135, in main
  File "madmeasurer\__init__.py", line 39, in search_path
  File "madmeasurer\__init__.py", line 60, in open_and_process_bd
Exception: Failed to get titles
[36180] Failed to execute script __main__

**Comment by 3ll3d00d** [comment]
What is the full path to the offending file?

**Comment by jmone1** [comment]
I've a few now such as the following (note: I've moved these from "Discs" to "Discs2" as I find them:
M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV
M:\Media\Discs2\Pixar Short Films Collection Vol 2\BDMV
M:\Media\Discs2\The Big Bang Theory S6 D1\BDMV
M:\Media\Discs2\THE_BIG_BANG_THEORY_S1_D1\BDMV
M:\Media\Discs2\The Walking Dead S3 D5\BDMV

Similar named items (eg others in the series ripped and named the same way) work fine

**Comment by jmone1** [comment]
Got them all segragated out now (18 from over 1,000).  Latest path was very simple:
M:\Media\Discs2\Zulu\BDMV

**Comment by 3ll3d00d** [comment]
so it's blowing up in libbluray by the looks of it

can you run it against 1 such BD with -vvv and then paste the entire output?

**Comment by jmone1** [comment]
C:\Users\natha\Downloads\MadMeasure>madmeasurer.exe -vvv --main-by-jriver -m  "M:\Media\Discs2\Gameofthrones S4 Disc5"
2019-07-26 17:28:45,390 - Searching M:\Media\Discs2\Gameofthrones S4 Disc5/**/BDMV/index.bdmv
2019-07-26 17:28:45,463 - Opening M:\Media\Discs2\Gameofthrones S4 Disc5
bluray.c:1413: libbluray version 1.1.1
bluray.c:1438: BLURAY initialized!
aacs.c:83: AACS\Unit_Key_RO.inf not found. No AACS protection.
navigation.c:476: Disc has no property(MainFeature)
navigation.c:479: Disc has no property(Playlists)
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature Gene
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature Gene
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature Gene
navigation.c:519: Discarding on min title length (00011.mpls)
navigation.c:519: Discarding on min title length (00020.mpls)
navigation.c:519: Discarding on min title length (00050.mpls)
navigation.c:519: Discarding on min title length (00053.mpls)
navigation.c:519: Discarding on min title length (00060.mpls)
navigation.c:519: Discarding on min title length (00500.mpls)
navigation.c:519: Discarding on min title length (00750.mpls)
navigation.c:519: Discarding on min title length (00751.mpls)
navigation.c:519: Discarding on min title length (00800.mpls)
navigation.c:519: Discarding on min title length (00801.mpls)
navigation.c:519: Discarding on min title length (00802.mpls)
bluray.c:1553: BLURAY destroyed!
Traceback (most recent call last):
  File "madmeasurer\__main__.py", line 139, in <module>
  File "madmeasurer\__main__.py", line 135, in main
  File "madmeasurer\__init__.py", line 39, in search_path
  File "madmeasurer\__init__.py", line 60, in open_and_process_bd
Exception: Failed to get titles
[38096] Failed to execute script __main__

C:\Users\natha\Downloads\MadMeasure>pause
Press any key to continue . . .

**Comment by jmone1** [comment]
I'd suggest that if libbluray fails, then just skip it and move to the next one.  All the ones that I have that are failing don't have an HDR section anyway.

**Comment by 3ll3d00d** [comment]
Can you try running with `--bd-debug-mask=0xFFFFF` and see what you get?

If it crashes in libbluray then that is not something I can handle unfortunately unless I patch libbluray

**Comment by jmone1** [comment]
```
C:\Users\natha\Downloads\MadMeasure>madmeasurer.exe -vvv --main-by-jriver --bd-debug-mask=0xFFFFF -m "M:\Media\Discs2\Gameofthrones S4 Disc5"
2019-07-26 18:16:34,520 - Overriding BD_DEBUG_MASK - 0xFFFFF
2019-07-26 18:16:34,521 - Searching M:\Media\Discs2\Gameofthrones S4 Disc5/**/BDMV/index.bdmv
2019-07-26 18:16:34,530 - Opening M:\Media\Discs2\Gameofthrones S4 Disc5
bluray.c:1413: libbluray version 1.1.1
bluray.c:1438: BLURAY initialized!
dir_win32.c:111: Opening WIN32 dir M:\Media\Discs2\Gameofthrones S4 Disc5... (0000024830D7ECC0)
dir_win32.c:51: Closed WIN32 dir (0000024830D7ECC0)
disc.c:337: M:\Media\Discs2\Gameofthrones S4 Disc5 does not seem to be image file or device node
file_win32.c:121: Error opening file M:\Media\Discs2\Gameofthrones S4 Disc5\AACS\Unit_Key_RO.inf
aacs.c:83: AACS\Unit_Key_RO.inf not found. No AACS protection.
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\index.bdmv (0000024830E1BC50)
file_win32.c:47: Closed WIN32 file (0000024830E1BC50)
bdj.c:148: JRE version: 1.8
bdj.c:166: JavaHome: C:\Program Files\Java\jre1.8.0_161
bdj.c:188: can't open library 'C:\Program Files\Java\jre1.8.0_161\bin\client\jvm.dll'
bdj.c:453: JAVA_HOME not set, trying default locations
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:310: Opening \jre\bin\server\jvm ...
dl_win32.c:91: can't open library '\jre\bin\server\jvm': The specified module could not be found.
bdj.c:310: Opening \bin\server\jvm ...
dl_win32.c:91: can't open library '\bin\server\jvm': The specified module could not be found.
bdj.c:310: Opening \jre\bin\client\jvm ...
dl_win32.c:91: can't open library '\jre\bin\client\jvm': The specified module could not be found.
bdj.c:310: Opening \bin\client\jvm ...
dl_win32.c:91: can't open library '\bin\client\jvm': The specified module could not be found.
bdj.c:746: BD-J check: Failed to load JVM library
dir_win32.c:111: Opening WIN32 dir M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\META\DL... (0000024830D7ED20)
dir_win32.c:51: Closed WIN32 dir (0000024830D7ED20)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\META\DL\bdmt_eng.xml (0000024830E1C8D0)
file_win32.c:47: Closed WIN32 file (0000024830E1C8D0)
meta_parse.c:228: using default disclib language 'eng'
file_win32.c:121: Error opening file M:\Media\Discs2\Gameofthrones S4 Disc5\CERTIFICATE\id.bdmv
disc.c:424: error opening file CERTIFICATE\id.bdmv
file_win32.c:121: Error opening file M:\Media\Discs2\Gameofthrones S4 Disc5\CERTIFICATE\BACKUP\id.bdmv
disc.c:424: error opening file CERTIFICATE\BACKUP\id.bdmv
bdj.c:148: JRE version: 1.8
bdj.c:166: JavaHome: C:\Program Files\Java\jre1.8.0_161
bdj.c:188: can't open library 'C:\Program Files\Java\jre1.8.0_161\bin\client\jvm.dll'
bdj.c:453: JAVA_HOME not set, trying default locations
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:323: Opening jvm ...
dl_win32.c:91: can't open library 'jvm': The specified module could not be found.
bdj.c:310: Opening \jre\bin\server\jvm ...
dl_win32.c:91: can't open library '\jre\bin\server\jvm': The specified module could not be found.
bdj.c:310: Opening \bin\server\jvm ...
dl_win32.c:91: can't open library '\bin\server\jvm': The specified module could not be found.
bdj.c:310: Opening \jre\bin\client\jvm ...
dl_win32.c:91: can't open library '\jre\bin\client\jvm': The specified module could not be found.
bdj.c:310: Opening \bin\client\jvm ...
dl_win32.c:91: can't open library '\bin\client\jvm': The specified module could not be found.
bdj.c:746: BD-J check: Failed to load JVM library
dir_win32.c:111: Opening WIN32 dir M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST... (0000024830D7EE80)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\MovieObject.bdmv (0000024830E1C690)
file_win32.c:47: Closed WIN32 file (0000024830E1C690)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\index.bdmv (0000024830E1C610)
file_win32.c:47: Closed WIN32 file (0000024830E1C610)
properties.c:55: Properties file C:\Users\natha\AppData\Roaming\bluray\properties\P68998cbcb8f726be6c1b7302f600c7b600000000 does not exist
navigation.c:476: Disc has no property(MainFeature)
properties.c:55: Properties file C:\Users\natha\AppData\Roaming\bluray\properties\P68998cbcb8f726be6c1b7302f600c7b600000000 does not exist
navigation.c:479: Disc has no property(Playlists)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00800_MediaInfo.txt (0000024830E1BFD0)
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature Gene
file_win32.c:47: Closed WIN32 file (0000024830E1BFD0)
file_win32.c:121: Error opening file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\BACKUP\PLAYLIST\00800_MediaInfo.txt
disc.c:424: error opening file BDMV\BACKUP\PLAYLIST\00800_MediaInfo.txt
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00801_MediaInfo.txt (0000024830E1BFD0)
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature Gene
file_win32.c:47: Closed WIN32 file (0000024830E1BFD0)
file_win32.c:121: Error opening file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\BACKUP\PLAYLIST\00801_MediaInfo.txt
disc.c:424: error opening file BDMV\BACKUP\PLAYLIST\00801_MediaInfo.txt
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00802_MediaInfo.txt (0000024830E1C450)
bdmv_parse.c:55: bdmv_parse_header(MPLS): invalid signature Gene
file_win32.c:47: Closed WIN32 file (0000024830E1C450)
file_win32.c:121: Error opening file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\BACKUP\PLAYLIST\00802_MediaInfo.txt
disc.c:424: error opening file BDMV\BACKUP\PLAYLIST\00802_MediaInfo.txt
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00011.mpls (0000024830E1C610)
file_win32.c:47: Closed WIN32 file (0000024830E1C610)
navigation.c:519: Discarding on min title length (00011.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00020.mpls (0000024830E1C350)
file_win32.c:47: Closed WIN32 file (0000024830E1C350)
navigation.c:519: Discarding on min title length (00020.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00050.mpls (0000024830E1C410)
file_win32.c:47: Closed WIN32 file (0000024830E1C410)
navigation.c:519: Discarding on min title length (00050.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00053.mpls (0000024830E1C8D0)
file_win32.c:47: Closed WIN32 file (0000024830E1C8D0)
navigation.c:519: Discarding on min title length (00053.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00060.mpls (0000024830E1CA10)
file_win32.c:47: Closed WIN32 file (0000024830E1CA10)
navigation.c:519: Discarding on min title length (00060.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00500.mpls (0000024830E1C210)
file_win32.c:47: Closed WIN32 file (0000024830E1C210)
navigation.c:519: Discarding on min title length (00500.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00750.mpls (0000024830E1C8D0)
file_win32.c:47: Closed WIN32 file (0000024830E1C8D0)
navigation.c:519: Discarding on min title length (00750.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00751.mpls (0000024830E1C510)
file_win32.c:47: Closed WIN32 file (0000024830E1C510)
navigation.c:519: Discarding on min title length (00751.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00800.mpls (0000024830E1BDD0)
file_win32.c:47: Closed WIN32 file (0000024830E1BDD0)
navigation.c:519: Discarding on min title length (00800.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00801.mpls (0000024830E1C550)
file_win32.c:47: Closed WIN32 file (0000024830E1C550)
navigation.c:519: Discarding on min title length (00801.mpls)
file_win32.c:140: Opened WIN32 file M:\Media\Discs2\Gameofthrones S4 Disc5\BDMV\PLAYLIST\00802.mpls (0000024830E1BE50)
file_win32.c:47: Closed WIN32 file (0000024830E1BE50)
navigation.c:519: Discarding on min title length (00802.mpls)
dir_win32.c:51: Closed WIN32 dir (0000024830D7EE80)
bluray.c:1553: BLURAY destroyed!
Traceback (most recent call last):
  File "madmeasurer\__main__.py", line 139, in <module>
  File "madmeasurer\__main__.py", line 135, in main
  File "madmeasurer\__init__.py", line 39, in search_path
  File "madmeasurer\__init__.py", line 60, in open_and_process_bd
Exception: Failed to get titles
[35144] Failed to execute script __main__
```

**Comment by jmone1** [comment]
Another Idea could some form of "Skip if Already Scanned"?  Write out a LogFile of what has previously been scanned by path and just skip these directorys.  I'd just add these ones manually.

**Comment by 3ll3d00d** [comment]
the log says that it discarded every track as being too short as it sets the min duration to 30mins (i.e. is looking for main titles)

try running with `--min-duration=10` and see if it completes normally

**Comment by jmone1** [comment]
--min-duration=10 still crashed on a disc
--min-duration=5 processed all discs without crashing! :)

**Comment by 3ll3d00d** [comment]
cool thanks, I'll just add some error handling for this case then as it shouldn't blow up just because the disc has too few tracks

**Comment by jmone1** [comment]
Just running it over my entire library using --min-duration=5 and it is now generating more measurement files.  Should I stop this?

**Comment by jmone1** [comment]
I guess it does not hurt :) !

**Comment by 3ll3d00d** [comment]
it will not overwrite existing files unless you tell it to

I would not expect changing the min duration to change which title is calculated as the main title (using any algorithm) 

hence the only reason I can think of is that you have some discs containing HDR content where no tracks are >30min long? extras discs maybe? 

what is it actually measuring?

**Comment by jmone1** [comment]
I'll let it run and report back but FYI many of my discs have multiple measurement files.  I'm happy about this as it will cover alt endings etc which is great.  One that was just picked up is in "Black Hawk Down" - 23min9s 00429.mpls  - I'll see what it actually is once it is finished doing it's stuff.

**Comment by 3ll3d00d** [comment]
https://github.com/3ll3d00d/madmeasurer/releases/tag/0.13.0 should handle this case more gracefully 

```
$ madmeasurer.exe --min-duration=300 -vvv w:\Aquaman
2019-07-27 08:46:51,461 - w:\Aquaman has no titles longer than 300, ignoring
2019-07-27 08:46:51,461 - Closing w:\Aquaman
2019-07-27 08:46:51,461 - Completed search of w:\Aquaman/**/BDMV/index.bdmv, processed 1 BD
```
